config/routes.rb
Rails.application.routes.draw do
  root 'tools#index'
  devise_for :users

  resources :users, except: [:new, :create]
  resources :categories, only: [:index, :show]
  resources :tools do
    resources :reviews, except: [:show, :index]
  end
  resources :reviews, only: [:new, :create, :show, :index] do
    resources :comments, except: [:show, :index]
    resources :votes, only: [:create, :update]
  end
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  belongs_to :user
  belongs_to :category

  validates :user, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :category, presence: true

  def average_stars
    return "" if reviews.empty?
    '<i class="fa fa-wrench"></i>' * reviews.average(:rating)
  end

  def self.search(query)
    where("name ilike ?", "%#{query}%")
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_tool, only: [:destroy]
  before_action :authorize_user, only: [:destroy]

  def index
    if params[:search]
      @tools = Tool.search(params[:search]).order(:name).page(params[:page]).per(10)
    else
      @tools = Tool.order(:name).page(params[:page]).per(10)
    end
  end

  def show
    @tool = Tool.find(params[:id])
    @reviews = @tool.reviews
    @review = Review.new
    @comment = Comment.new
    @category = @tool.category
  end

  def new
    @tool = Tool.new
    @categories = Category.all
  end

  def create
    @tool = Tool.new(tool_params)
    @tool.user = current_user
    if @tool.save
      flash[:success] = "Successfully created a new dev tool!"
      redirect_to @tool
    else
      @categories = Category.all
      flash[:warning] = "Form errors"
      render :new
    end
  end

  def edit
    @tool = Tool.find(params[:id])
    @categories = Category.all
  end

  def update
    @tool = Tool.find(params[:id])
    @tool.update(tool_params)
    if @tool.save
      flash[:info] = "Tool updated"
      redirect_to tool_path(@tool)
    else
      @categories = Category.all
      flash[:warning] = "Form errors"
      render :edit
    end
  end

  def destroy
    @tool = Tool.find(params[:id])
    @tool.destroy
    flash[:success] = "Tool deleted"
    redirect_to tools_path
  end

  private
  def set_tool
    @tool = Tool.find(params[:id])
  end

  def authorize_user
    unless current_user == @tool.user || current_user.admin?
      raise ActionController::RoutingError.new("Not Found")
    end
  end

  def tool_params
    params.require(:tool).permit(:name, :category_id, :description)
  end
end

app/views/tools/_comments_section.html.erb
<ul class="comment-list">
  <% review.comments.each do |comment| %>
    <li>
      <% if current_user && (current_user.admin? || current_user == comment.user) %>
        <ul class="inline-list">
          <li><%= link_to "Edit Comment", edit_review_comment_path(comment.review, comment), method: :get %></li>
          <li><%= link_to "Delete Comment", review_comment_path(comment.review, comment), method: :delete %></li>
        </ul>
      <% end %>

      <p class="user-attribution"><%= "#{comment.user.email} opines on this opinion: " %></p>
      <p><%= comment.body %></p>
    </li>
  <% end %>
</ul>

<ul class="accordion new-comment-form" data-accordion>
  <li class="accordion-navigation">
    <%= link_to "Add a comment", "#comment-form#{review.id}" %>

    <div id= <%="comment-form#{review.id}"%> class="content comment-form">
      <%= form_for [review, @comment] do |f| %>
        <%= render "layouts/form_errors", object: f.object %>

        <%= f.text_area :body %>
        <%= f.submit 'Submit comment', class: "small button radius" %>
      <% end %>
    </div>

  </li>
</ul>

app/views/tools/_form_for.html.erb
<%= form_for @tool do |f| %>
  <%= render "layouts/form_errors", object: f.object %>

  <div class="small-12 medium-7 column">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="small-12 medium-5 column">
    <%= f.label :category_id, "Category" %>
    <%= f.select :category_id, options_from_collection_for_select(@categories, "id", "name"), prompt: "Select a category" %>
  </div>

  <div class="small-12 column">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 10 %>
    <%= f.submit "Submit", class: "button radius" %>
  </div>

<% end %>

app/views/tools/_new_review.html.erb
<div class="content" id="review-form">

  <%= form_for [@tool, @review] do |f| %>
  <div class="medium-6 column">
    <%= f.label :rating, "My rating" %>
    <%= f.select :rating, [nil, ['★', 1], ['★★', 2], ['★★★', 3], ['★★★★', 4], ['★★★★★', 5] ] %>
  </div>
  <div class="small-12 column">
    <%= f.label :body, "My review" %>
    <%= f.text_area :body, rows: "10" %>
    <%= f.submit 'Submit', class: "button radius" %>
  </div>
  <% end %>

</div>

app/views/tools/_review.html.erb
<% unless review.body.empty? %>
<div class="review">
  <% if current_user && (current_user.admin? || review.user) %>
    <%= button_to "Delete review #{review.id}",
    tool_review_path(review.tool, review), method: :delete,
    class: "small button radius" %>
  <% end %>

  <p><%= review.star_rating %></p>
  <p><%= review.body %></p>
  <% if user_signed_in? %>
    <div class='vote-area'>
      <a href="#" class="upvote" user-id="<%= current_user.id %>"
        review-id="<%= review.id %>" tool-id= "<%= @tool.id %>"
        id="upvote-<%= review.id %>"> ▲ </a>
      <a href="#" class="downvote" user-id="<%= current_user.id %>"
        review-id="<%= review.id %>" tool-id= "<%= @tool.id %>" 
        id="downvote-<%= review.id %>"> ▼ </a>
      <div id="vote-count-<%= review.id %>">Score: <%= review.vote_count %></div>
    </div>
  <% end %>
  <%= link_to "#{review.comments.count} comment(s)", "#", class: "comment-toggle" %>

  <div class="small-12 column comment-div" hidden>
    <%= render partial: "comments_section", locals: {review: review} %>
  </div>
</div>
<% end %>

app/views/tools/edit.html.erb
<div class="small-12 column">
  <h1>Edit tool</h1>
</div>

<%= render "form_for" %>

<div class="small-12 column">
  <%= link_to "Cancel", @tool %>
</div>

app/views/tools/index.html.erb
<div class="row">
  <div class="small-12 column">
    <% if params[:search] %>
      <h1>Search Results</h1>
    <% else %>
      <h1>Dev Tools</h1>
    <% end %>
  </div>

  <div class="small-12 column">
    <h6><%= "No results found." if params[:search] && @tools.empty? %></h6>

    <ul class="no-bullet">
      <% @tools.each do |tool| %>
        <li class="tool-list-item">
          </h2><%= link_to tool.name, tool_path(tool.id) %><h2>
          <p><%= tool.description %></p>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<%= link_to "Add a dev tool!", new_tool_path %>

<%= paginate @tools %>

app/views/tools/new.html.erb
<h1>Add a new tool</h1>

<%= form_for @tool do |f| %>

  <div class="small-12 medium-7 column">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="small-12 medium-5 column">
    <%= f.label :category_id, "Category" %>
    <%= f.select :category_id, options_from_collection_for_select(@categories, "id", "name"), prompt: "Select a category" %>
  </div>

  <div class="small-12 column">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 10 %>
    <%= f.submit "Submit", class: "button radius" %>
  </div>
<% end %>

<div class="small-12 column">
    <%= link_to "Cancel", tools_path %>
</div>

app/views/tools/show.html.erb
<div class="row tool-info">
  <%= link_to @category.name, @category %>
  <h1><%= @tool.name %></h1>
  <p><%= @tool.description %></p>
  <% if current_user && (current_user.admin? || current_user == @tool.user) %>
    <ul class="inline-list">
      <li><%= link_to "Edit Tool", edit_tool_path(@tool), method: :get %></li>
      <li><%= link_to "Delete Tool", tool_path(@tool), method: :delete %></li>
    </ul>
  <% end %>
</div>

<div class="row">
  <h3>Reviews</h3>
  <h6><%= "#{@tool.reviews.count} reviews—average rating: " %><%= @tool.average_stars.html_safe %></h6>


  <%= render @reviews %>
</div>

<div class="row">
  <ul class="accordion new-review-form" data-accordion>
    <li class="accordion-navigation">
      <%= link_to "Add your own review of #{@tool.name}", "#review-form" %>
      <%= render "reviews/form_for" %>
    </li>
  </ul>
</div>