config/routes.rb
Rails.application.routes.draw do
  root 'tools#index'
  devise_for :users

  resources :users, except: [:new, :create]
  resources :categories, only: [:index, :show]
  resources :tools do
    resources :reviews, except: [:show, :index]
  end
  resources :reviews, only: [:new, :create, :show, :index] do
    resources :comments, except: [:show, :index]
    resources :votes, only: [:create, :update]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :set_review, only: [:destroy]
  before_action :authorize_user, only: [:destroy]


  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:success] = "Review deleted"
    redirect_to tool_path(@review.tool)
  end

  def create
    @tool = Tool.find(params[:tool_id])
    @review = Review.new(review_params)
    @review.tool = @tool
    @review.user = current_user

    if @review.save
      flash[:success] = "Success"
      # ReviewMailer.new_review(@review).deliver_later
      redirect_to tool_path(@tool)
    else
      @reviews = @tool.reviews
      @comment = Comment.new
      @category = @tool.category
      flash[:warning] = "Form errors"
      render "tools/show"
    end
  end

  def edit
    @review = Review.find(params[:id])
    @tool = @review.tool
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    @tool = @review.tool
    if @review.save
      flash[:info] = "Review updated"
      redirect_to @tool
    else
      flash[:warning] = "Form errors"
      render :edit
    end
  end

  private
  def set_review
    @review = Review.find(params[:id])
  end

  def authorize_user
    unless current_user == @review.user || current_user.admin?
      raise ActionController::RoutingError.new("Not Found")
    end
  end

  def review_params
    params.require(:review).permit(:rating, :body, :tool_id)
  end
end

app/views/reviews/_form_for.html.erb
<div class="content" id="review-form">

  <%= form_for [@tool, @review] do |f| %>
    <%= render "layouts/form_errors", object: f.object %>

  <div class="medium-6 column">
    <%= f.label :rating, "My rating" %>
    <%= f.select :rating, [nil, ['★', 1], ['★★', 2], ['★★★', 3], ['★★★★', 4], ['★★★★★', 5] ] %>
  </div>
  <div class="small-12 column">
    <%= f.label :body, "My review" %>
    <%= f.text_area :body, rows: "10" %>
    <%= f.submit 'Submit', class: "button radius" %>
  </div>
  <% end %>

</div>

app/views/reviews/_review.html.erb
<% unless review.body.empty? %>
<div class="row review">
  <div class="small-12 columns">
    <% if current_user && (current_user.admin? || current_user == review.user) %>
      <ul class="inline-list">
        <li><%= link_to "Edit Review", edit_tool_review_path(review.tool, review), method: :get %></li>
        <li><%= link_to "Delete Review", tool_review_path(review.tool, review), method: :delete %></li>
      </ul>
    <% end %>
  </div>

  <div class="small-1 column">
    <% if user_signed_in? %>
      <div class="vote-area text-center">
        <a href="#" class="upvote" user-id="<%= current_user.id %>"
          review-id="<%= review.id %>" tool-id= "<%= @tool.id %>"
          id="upvote-<%= review.id %>"> ▲ </a>
        <div class="text-center" id="vote-count-<%= review.id %>"><h5><%= review.vote_count %></h5></div>
        <a href="#" class="downvote" user-id="<%= current_user.id %>"
          review-id="<%= review.id %>" tool-id= "<%= @tool.id %>"
          id="downvote-<%= review.id %>"> ▼ </a>
      </div>
    <% end %>
  </div>

  <div class="small-11 columns">
    <p><%= review.star_rating.html_safe %></p>
    <p><%= review.body %></p>
    <%= link_to "#{review.comments.count} comment(s)", "#", class: "comment-toggle" %>
  </div>

  <div class="small-12 column comment-div" hidden>
    <%= render partial: "tools/comments_section", locals: {review: review} %>
  </div>
</div>
<% end %>

app/views/reviews/edit.html.erb
<div class="small-12 column">
  <h1>Edit review</h1>
</div>

<%= render "form_for" %>

<div class="small-12 column">
  <%= link_to "Cancel", @tool %>
</div>