config/routes.rb
Rails.application.routes.draw do
  root 'tools#index'
  devise_for :users

  resources :users, except: [:new, :create]
  resources :categories, only: [:index, :show]
  resources :tools do
    resources :reviews, except: [:show, :index]
  end
  resources :reviews, only: [:new, :create, :show, :index] do
    resources :comments, except: [:show, :index]
    resources :votes, only: [:create, :update]
  end
end

app/views/layouts/_form_errors.html.erb
<% if object.errors.any? %>
  <div class="small-12 columns error-div">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevToolsReview</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to image_tag("Logo"), root_path %></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <li class="has-dropdown not-click">
          <%= link_to "Categories", categories_path %>
          <ul class="dropdown">
            <% @categories.each do |category| %>
              <li> <%= link_to category.name, category_path(category.id) %> </li>
            <% end %>
          </ul>
        </li>

        <li class="has-form">
          <%= form_tag(tools_path, method: "get", id: "search-form", class: "search-form") do %>
          <div class="row collapse">
            <div class="large-8 small-9 columns">
              <%= text_field_tag :search, params[:search], placeholder: "Search for a tool", id: "search-form-box" %>
            </div>
            <div class="large-4 small-3 columns">
              <%= submit_tag "Search", :name => nil, class: "alert button expand" %>
            </div>
          </div>
          <% end %>
        </li>

        <%- if current_user -%>
          <li><%= link_to 'My Account', user_path(current_user) %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>


  <div class="row">
    <div class="small-12 column background-box">

      <% flash.each do |key, value| %>
        <div data-alert class="alert-box <%= key %> radius">
          <%= value %>
          <a href="#" class="close">&times;</a>
        </div>
      <%- end -%>

      <%= yield %>

      <%= javascript_include_tag 'application' %>
      <%= yield :extra_footer %>
    </div>
  </div>

</body>
</html>